variable "region" {}
variable "account_environment" {}
variable "team_name" {}
variable "image_name" {}
variable "task_family_name" {}
variable "port" {}
variable "ecs_role" {}
variable "ecs_cluster_id" {}
variable "replicas" {}
variable "application_sg" {}
variable "private_subnets" {}
variable "service_tg_arn" {}