name: CI/CD for ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t supermarket-ecr .

      - name: Run tests
        run: docker run supermarket-ecr mvn clean test

  push-to-ecr:
    runs-on: self-hosted

    needs: build-and-test

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::211125330084:role/infra-provisioning-role
      - name: Tag Docker image
        run: docker tag supermarket-ecr:latest ${{ steps.ecr_login.outputs.registry }}/supermarket-ecr:latest

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ steps.ecr_login.outputs.registry }}/supermarket-ecr:latest

#  deploy-to-ecs:
#    runs-on: ubuntu-latest
#
#    needs: push-to-ecr
#
#    steps:
#      - name: Deploy to ECS
#        uses: aws-actions/amazon-ecs-deploy-task@v2
#        with:
#          cluster: accolite-devl-ecs-cluster
#          task-definition: ecs-accolite-devl-port8080-service
#          service: ecs-accolite-devl-port8080-service-service
#          image: ${{ needs.push-to-ecr.outputs.registry }}/supermarket-ecr:latest
#          region: us-east-1
